#! /bin/sh
echo 23 > /sys/class/gpio/export
echo 24 > /sys/class/gpio/export
echo 25 > /sys/class/gpio/export
echo 17 > /sys/class/gpio/export
echo 27 > /sys/class/gpio/export
echo 18 > /sys/class/gpio/export
echo 15 > /sys/class/gpio/export
